# Generated by Django 5.1.6 on 2025-02-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmodel',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='logmodel',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
